[package]
name = "lighty-cache"
version = "2026.2.1"
edition = "2021"

[dependencies]
lighty-models = { path = "../models" }
lighty-config = { path = "../config" }
lighty-events = { path = "../events" }
lighty-scanner = { path = "../scanner" }
lighty-storage = { path = "../storage" }
lighty-file-diff = { path = "../file-diff" }
lighty-file-cache = { path = "../file-cache" }
lighty-cdn = { path = "../cdn" }
dashmap = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
notify = { workspace = true }
chrono = { workspace = true }
futures = "0.3"
