[package]
name = "lighty-cdn"
version = "2026.2.1"
edition = "2021"

[dependencies]
lighty-events = { path = "../events" }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }

[dev-dependencies]
wiremock = { workspace = true }
serde_json = "1.0"
