[package]
name = "lighty-config"
description = "Configuration schema for LightyUpdater (no I/O)"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
