[package]
name = "lighty-app"
description = "LightyUpdater server binary"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[features]
default = []
s3 = ["lighty-runtime/s3"]

[[bin]]
name = "lighty-app"
path = "main.rs"

[dependencies]
lighty-runtime = { workspace = true }
tokio = { workspace = true }
