[package]
name = "lighty-scanner"
description = "Parallel scanning of server components (client / libraries / mods / natives / assets)"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
lighty-models  = { workspace = true }
lighty-config  = { workspace = true }
lighty-utils   = { workspace = true }
lighty-storage = { workspace = true }
tokio     = { workspace = true }
futures   = { workspace = true }
walkdir   = { workspace = true }
serde     = { workspace = true }
thiserror = { workspace = true }
tracing   = { workspace = true }
