[package]
name = "lighty-updater"
description = "Unified interface for LightyUpdater — Minecraft distribution server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
readme = "../README.md"
keywords = ["minecraft", "launcher", "server", "distribution"]
categories = ["games", "web-programming::http-server"]

[lib]
path = "lib.rs"

[dependencies]
lighty-models     = { workspace = true }
lighty-events     = { workspace = true }
lighty-utils      = { workspace = true }
lighty-file-system = { workspace = true }
lighty-config     = { workspace = true }
lighty-scanner    = { workspace = true }
lighty-cache      = { workspace = true }
lighty-watcher    = { workspace = true }
lighty-api        = { workspace = true }
